query GetEventByCheckinCode($code: String!) {
  eventByCheckinCode(code: $code) {
    id
    title
    description
    location_name
    start_date_time
    end_date_time
    is_registered
    checkin_code
    facilitator {
      privy_id
      display_name
      username
      avatar_url
    }
  }
}
